version: "3.7"

services:
  db_dev:
    image: postgres:12-alpine
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data/
  web_dev:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    command: python /code/manage.py runserver 0.0.0.0:8000
    env_file: .env
    environment:
      - DEBUG=1
      - SQL_HOST=db_dev
    ports:
      - 8000:8000
    volumes:
      - ./app/:/code
    depends_on:
      - db_dev
volumes:
  postgres_data_dev: