version: "3.7"

services:
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn test_planner.wsgi -b 0.0.0.0:8000
    env_file: .env
    environment:
      - DEBUG=0
    volumes:
      - static_files:/code/staticfiles
    expose:
      - 8000
    depends_on:
      - db
  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
    volumes:
      - static_files:/code/staticfiles
volumes:
  postgres_data:
  static_files: