version: "3.7"

services:
  db:
    image: postgres:12-alpine
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: unless-stopped
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
      args:
        - buildno=23
    command: gunicorn test_planner.wsgi -b 0.0.0.0:8000
    env_file: .env
    environment:
      - DEBUG=0
    volumes:
      - static_files:/code/staticfiles
    expose:
      - 8000
    depends_on:
      - db
    restart: unless-stopped
  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
    volumes:
      - static_files:/code/staticfiles
      - letsencrypt:/etc/letsencrypt
      - www-certbot:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    restart: unless-stopped
  certbot:
    image: certbot/certbot
    volumes:
      - letsencrypt:/etc/letsencrypt
      - www-certbot:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    restart: unless-stopped
volumes:
  postgres_data:
  static_files:
  letsencrypt:
  www-certbot:
