version: "3.7"

services:
  db:
    image: postgres:12-alpine
    environment:
      - TZ=Europe/Amsterdam
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: unless-stopped
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
      args:
        - buildno=31
    command: gunicorn test_planner.wsgi -b 0.0.0.0:8000
    env_file: .env
    environment:
      - DEBUG=0
    volumes:
      - ./staticfiles:/code/staticfiles
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: unless-stopped
volumes:
  postgres_data: