version: "3.7"

services:
  db:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    build: ./app
    entrypoint: ./docker-entrypoint.sh
    environment:
      - DEBUG=0
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_NAME=postgres
      - SQL_USER=postgres
      - SQL_HOST=db
      - SQL_PORT=5432
    ports:
      - 8000:8000
    depends_on:
      - db
#  nginx:

volumes:
  postgres_data: